version: "3.9"
services:
  web:
    build: .
    volumes:
         - ./:/usr/share/nginx/html
    ports:
      - "90:80"
  nginx:
    image: "nginx:alpine"
    volumes:
         - ./:/usr/share/nginx/html